const coverImage = [
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/71HLiMMNe-L.jpg'
  },
  {
    a:'http://www.movienewsletters.net/photos/072500R1.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/91DoU3%2BT-6L._SY445_.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/51K0R5DNFEL._SY445_.jpg'
  },
  {
    a:'https://upload.wikimedia.org/wikipedia/en/4/46/OYpost.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/81zDita2ncL._SY679_.jpg'
  },
  {
    a:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC68-pgMFvqh0SaXKWjOt7dAB6rHK2gTwjDIJzaOWOeWEr-s_tgQ'
  },
  {
    a:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5CUDPv20zETjcg26J8u-x_IFc8oOjbM-ytZOJwirOTmSHfRjY'
  },
  {
    a:'https://fesapusewebsite.blob.core.windows.net/fathom/pm3-ebcc7fc25746777807a80210e22d95c8.jpg'
  },
  {
    a:'http://barkerhost.com/wp-content/uploads/sites/4/2015/06/tuKO2PLGDcJj5vpfAYKSQcnLEpD-0.jpg'
  },
  {
    a:'https://m.media-amazon.com/images/M/MV5BOGJjNzZmMmUtMjljNC00ZjU5LWJiODQtZmEzZTU0MjBlNzgxL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/51Y9GA5ZTPL.jpg'
  },
  {
    a:'https://fesapusewebsite.blob.core.windows.net/fathom/howls3-49077fb5f658a5c95332976cfc61ee48.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/51qyfcSrd-L._SY445_.jpg'
  },
  {
    a:'https://fesapusewebsite.blob.core.windows.net/fathom/ponyo-1000x1480-r2-3c7dd4adc4c5119cdacef777caf4657a.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/51FfA9mOuiL._SX258_BO1,204,203,200_.jpg'
  },
  {
    a:'https://d2e111jq13me73.cloudfront.net/sites/default/files/styles/product_image_aspect_switcher_170w/public/product-images/csm-movie/from-up-on-poppy-hill.jpg?itok=seqcoEpX'
  },
  {
    a:'https://m.media-amazon.com/images/M/MV5BMTU4NDg0MzkzNV5BMl5BanBnXkFtZTgwODA3Mzc1MDE@._V1_.jpg'
  },
  {
    a:'https://s22319.pcdn.co/wp-content/uploads/Kaguya-Hime_no_Monogatari_poster1.jpg'
  },
  {
    a:'https://images-na.ssl-images-amazon.com/images/I/91Sruo1eOpL._SY445_.jpg'
  }
]

 export default coverImage;
